apiVersion: v1
kind: Service
metadata:
  name: {{ template "terraformsp.name" . }}
  labels:
  {{- include "terraformsp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "terraformsp.name" . }}
