# Default values for java-specific-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Docker Registry Secret name used to access a private repo
dockerRegistrySecretName: regcred

image:
  # -- Image repository
  registry: registry.gitlab.com/agilefactory/witboost.mesh/provisioning/terraform/witboost.mesh.provisioning.terraform.specificprovisioner
  # -- Image tag
  tag: to-be-replaced
  # -- The imagePullPolicy for a container and the tag of the image affect when the kubelet attempts to pull (download) the specified image.
  pullPolicy: Always

# -- define extra variables to add to the container(s)
# e.g:
# extraEnvVars:
#  - name: FOO
#     value: "10"
extraEnvVars: []

# -- readiness probe spec
readinessProbe: {}

# -- liveness probe spec
livenessProbe: {}

# -- security context spec
securityContext:
  runAsUser: 65535
  allowPrivilegeEscalation: false
  runAsNonRoot: true

# -- serviceAccount
serviceAccountName:

# -- resources spec
resources: {}

# -- Allows you to specify common labels
labels: {}

# -- This configuration allows you to override the application.conf file
configOverride: {}

# -- This configuration allows you to override the logback.xml file
logbackOverride: {}


